### ISSUE TITLE
parse routes config

### ISSUE THREAD

**Issue by winstonallo** [42-projects-abied-ch/webserv#42]
will implement a routes class with the info from the config, should be the last module of config parsing
**TODO:**
- [x]  parse the routes (prolly same way the servers were parsed)
- [x]  validate paths (paths exists, exec rights?)
- [x]  validate default files (path, extension, content)
- [x]  #43
